SELECT COUNT(q.ID_QUARTO) AS Quartos_Disponiveis, t.TIPO AS Tipo_Quarto, h.NOME AS Nome_Hotel 
FROM HOTEL h 
INNER JOIN QUARTO q ON h.ID_HOTEL = q.FK_HOTEL_ID_HOTEL 
INNER JOIN TIPOS t ON q.FK_TIPOS_ID_TIPO = t.ID_TIPO 
WHERE q.STATUS = FALSE 
GROUP BY h.NOME, t.TIPO 
ORDER BY h.NOME; 


SELECT HOTEL.NOME, FUNCIONARIO.CARGO, COUNT(*) AS NumeroDeFuncionarios 
FROM FUNCIONARIO 
JOIN HOTEL ON FUNCIONARIO.FK_HOTEL_ID_HOTEL = HOTEL.ID_HOTEL 
GROUP BY HOTEL.NOME, FUNCIONARIO.CARGO; 


SELECT h.NOME AS NOME_HOTEL, r.ID_RESERVA, DATE_FORMAT(r.CHECKIN, '%d/%m/%Y') AS CHECKIN,DATE_FORMAT(r.CHECKOUT, 	'%d/%m/%Y') 	AS 	CHECKOUT, 	DATEDIFF(r.CHECKOUT, r.CHECKIN) as DIAS_RESERVADOS, CONCAT('R$', FORMAT((t.PRECO * DATEDIFF(r.CHECKOUT, r.CHECKIN)), 2, 'de_DE')) AS RECEITA_TOTAL 
FROM HOTEL h 
JOIN QUARTO q ON h.ID_HOTEL = q.FK_HOTEL_ID_HOTEL 
JOIN RESERVA r ON q.ID_QUARTO = r.FK_QUARTO_ID_QUARTO 
JOIN TIPOS t ON q.FK_TIPOS_ID_TIPO = t.ID_TIPO 
GROUP BY h.NOME, r.ID_RESERVA 
ORDER BY r.ID_RESERVA, h.NOME; 


SELECT 	RESERVA.ID_RESERVA, 	HOSPEDE.NOME 	AS 	NomeHospede, 
DATE_FORMAT(RESERVA.CHECKIN, '%d/%m/%Y') AS CHECKIN, 
           DATE_FORMAT(RESERVA.CHECKOUT, '%d/%m/%Y') AS CHECKOUT, 
RESERVA.NUM_HOSPEDES, QUARTO.NUMERO AS NumeroQuarto, HOSPEDE.TELEFONE AS TelefoneHospede 
FROM RESERVA 
JOIN QUARTO ON RESERVA.FK_QUARTO_ID_QUARTO = QUARTO.ID_QUARTO 
JOIN HOSPEDE ON RESERVA.FK_HOSPEDE_ID_HOSPEDE = HOSPEDE.ID_HOSPEDE; 


SELECT F.NOME AS FUNCIONARIO, F.TELEFONE, DATE_FORMAT(F.ADMISSAO, '%d/%m/%Y') AS 
ADMISSAO, F.CARGO, H.NOME AS HOTEL 
FROM FUNCIONARIO F 
JOIN HOTEL H ON F.FK_HOTEL_ID_HOTEL = H.ID_HOTEL 
ORDER BY F.NOME; 
 

SELECT HOTEL.NOME, QUARTO.NUMERO, TIPOS.TIPO, 
CASE 
    WHEN QUARTO.STATUS = TRUE THEN  "RESERVADO" 
    ELSE "DISPONÍVEL" 
END AS DISPONIBILIDADE 
FROM QUARTO 
JOIN HOTEL ON QUARTO.FK_HOTEL_ID_HOTEL = HOTEL.ID_HOTEL 
JOIN TIPOS ON QUARTO.FK_TIPOS_ID_TIPO = TIPOS.ID_TIPO 
WHERE QUARTO.FK_HOTEL_ID_HOTEL = 1; 