DELIMITER // 
CREATE PROCEDURE ObterReservaPorID(IN client_id INT) 
BEGIN 
    SELECT R.ID_RESERVA, 
           DATE_FORMAT(R.CHECKIN, '%d/%m/%Y') AS CHECKIN, 
           DATE_FORMAT(R.CHECKOUT, '%d/%m/%Y') AS CHECKOUT, 
           R.NUM_HOSPEDES, 
           Q.NUMERO AS Quarto_Numero, 
           CONCAT('R$', FORMAT(T.preco, 2, 'de_DE')) AS Preco, 
           T.TIPO AS Tipo_Quarto, 
           H.NOME AS Hotel_Nome 
    FROM RESERVA R 
    JOIN QUARTO Q ON R.FK_QUARTO_ID_QUARTO = Q.ID_QUARTO 
    JOIN HOTEL H ON Q.FK_HOTEL_ID_HOTEL = H.ID_HOTEL 
    JOIN TIPOS T ON Q.FK_TIPOS_ID_TIPO = T.ID_TIPO 
    WHERE R.FK_HOSPEDE_ID_HOSPEDE = client_id; 
END; 
// 
DELIMITER ; 
CALL ObterReservaPorID(2); 

CREATE TABLE HOSPEDE_LOG ( 
    ID_AUDITORIA INT PRIMARY KEY auto_increment not null, 
    DATA_HORA DATETIME NOT NULL, 
    TIPO_OPERACAO VARCHAR(10) NOT NULL, 
    USERNAME VARCHAR(30) NOT NULL, 
    ID_HOSPEDE INT, 
    NOME_ANTIGO VARCHAR(50), 
    NOME_NOVO VARCHAR(50), 
    TELEFONE_ANTIGO VARCHAR(50), 
    TELEFONE_NOVO VARCHAR(50), 
    EMAIL_ANTIGO VARCHAR(100), 
    EMAIL_NOVO VARCHAR(100), 
    DATA_NASCIMENTO_ANTIGO DATE, 
    DATA_NASCIMENTO_NOVO DATE, 
    CPF_ANTIGO  VARCHAR(11), 
    CPF_NOVO VARCHAR(11) 
); 
DELIMITER $ 


CREATE TRIGGER HOSPEDE_LOG_Insert 
AFTER INSERT ON HOSPEDE 
FOR EACH ROW 
BEGIN 
    INSERT 	INTO 	HOSPEDE_LOG 	(DATA_HORA, 	TIPO_OPERACAO, 	USERNAME, NOME_NOVO, TELEFONE_NOVO, EMAIL_NOVO, DATA_NASCIMENTO_NOVO, CPF_NOVO, ID_HOSPEDE) 
    SELECT NOW(), 'INSERT', CURRENT_USER(), NEW.NOME, NEW.TELEFONE, NEW.EMAIL, NEW.DATA_NASCIMENTO, NEW.CPF, NEW.ID_HOSPEDE; 
END$ 
 
CREATE TRIGGER HOSPEDE_LOG_Update 
AFTER UPDATE ON HOSPEDE 
FOR EACH ROW 
BEGIN 
    INSERT INTO HOSPEDE_LOG (DATA_HORA, TIPO_OPERACAO, USERNAME, ID_HOSPEDE, NOME_ANTIGO, NOME_NOVO, TELEFONE_ANTIGO, TELEFONE_NOVO, EMAIL_ANTIGO, EMAIL_NOVO, DATA_NASCIMENTO_ANTIGO, DATA_NASCIMENTO_NOVO, CPF_ANTIGO, CPF_NOVO) 
    SELECT 	NOW(), 	'UPDATE', 	CURRENT_USER(), 	OLD.ID_HOSPEDE, 	OLD.NOME, NEW.NOME, 	OLD.TELEFONE, 	NEW.TELEFONE, 	OLD.EMAIL, 	NEW.EMAIL, OLD.DATA_NASCIMENTO, NEW.DATA_NASCIMENTO, OLD.CPF, NEW.CPF; 
END$ 
 
CREATE TRIGGER HOSPEDE_LOG_Delete 
AFTER DELETE ON HOSPEDE 
FOR EACH ROW 
BEGIN 
    INSERT 	INTO 	HOSPEDE_LOG 	(DATA_HORA, 	TIPO_OPERACAO, 	USERNAME, NOME_ANTIGO, TELEFONE_ANTIGO, EMAIL_ANTIGO, DATA_NASCIMENTO_ANTIGO, CPF_ANTIGO, ID_HOSPEDE) 
    SELECT NOW(), 'DELETE', CURRENT_USER(), OLD.NOME, OLD.TELEFONE, OLD.EMAIL, 
OLD.DATA_NASCIMENTO, OLD.CPF, OLD.ID_HOSPEDE; 
END$ 
DELIMITER ; 
